### ISSUE TITLE
Plugin not registering in latest version of SpongeForge

### ISSUE THREAD

**Issue by MastaC729** [Katrix-/ChitChat#2]
Forge Version: 12.18.1.2065
SpongeForge Version:  5.0.0.1674

The following stacktrace is thrown when the server starts up, thus stopping ChitChat from launching: http://pastebin.com/bL3km7iD

Let me know if you need any additional info.

**Comment by Katrix** [comment]
Problem is basically that the plugin is incompatible with API 5. I'm working on another project that will make targeting multiple API versions easier. Once I'm sure that thing is solid I'll look into this more.

I might make a quick patch to fix any incompatibilities in the meantime if it doesn't mean too much work. (Might disable some features though if they cause problems).
